#!/usr/bin/expect
# vpnc-login: spawns and controls vpnc-connect
# Copyright (c) 2005 by Fabian Franz.
# License: GPL, version 2
# $Id: vpnc-login 401 2011-01-09 18:33:05Z mariop $
#


# Syntax: vpnc-login configfile

set configfile [lindex $argv 0]


#stty -echo # gib keine Eingabezeichen aus
expect_user -re "user=(.*)#"
set user $expect_out(1,string)
expect_user -re "pass=(.*)\n"
set password $expect_out(1,string)
#stty echo # gib Eingabezeichen aus

set pid [spawn -noecho ./vpnc-connect "$configfile" ]

expect {
        "Secure memory is not locked into core" { exit 4 }
	"Enter username for" { send "$user\r"; sleep 1; exp_continue }
	"Enter password for"  { sleep 2; send "$password\r" }
	"vpnc found running *" { exit 3 }
}

expect {
	"VPNC started in background" { sleep 4; exit 0 }
	"/usr/sbin/vpnc: authentication unsuccessful" { exit 1 }
}
