#!/bin/bash

if [ $# -ne 2 ]; then
	echo "Usage: $0 architecture target"
	exit 1
fi

arch=$1
target=$(readlink -f $2)

wget ftp://ftp.berlios.de/pub/larch/larch7.2/i686/pacman-allin.tar.gz -O /tmp/pacman-allin.tar.gz
mkdir -p /tmp/pacman
tar -zxf /tmp/pacman-allin.tar.gz -C /tmp

cat > /tmp/pacman.conf << EOT
[options]
HoldPkg = pacman glibc
SyncFirst = pacman
[core]
Server = http://ftp.hadiko.de/pub/dists/arch/arch/\$repo/os/$arch 
[extra]
Server = http://ftp.hadiko.de/pub/dists/arch/arch/\$repo/os/$arch 
[community]
Server = http://ftp.hadiko.de/pub/dists/arch/arch/\$repo/os/$arch 
EOT

mkdir -p $target/var/lib/pacman
mkdir -p $target/var/cache/pacman/pkg

mkdir -p $target/dev
mkdir -p $target/sys
mkdir -p $target/proc
mkdir -p $target/root

mount --bind /dev $target/dev
mount --bind /proc $target/proc
mount --bind /sys $target/sys

cat > $target/root/.bashrc << EOT
alias ls='ls --color=auto'
PS1='[ARCH-CHROOT \u@\h \W]\$ '
export PATH=$PATH:/usr/local/bin
export LC_ALL=C
EOT

/tmp/pacman-allin/pacman --root $target --cachedir $target/var/cache/pacman/pkg --config /tmp/pacman.conf --noconfirm -Sy base base-devel

umount $target/dev
umount $target/proc
umount $target/sys

rm -rf /tmp/pacman
rm -f /tmp/pacman.conf

cat > $target/enter << EOT
#!/bin/bash

mount --bind /dev $target/dev
mount --bind /proc $target/proc
mount --bind /sys $target/sys
mount -t devpts none $target/dev/pts

cp /etc/resolv.conf $target/etc/resolv.conf

chroot $target /bin/bash

umount $target/sys
umount $target/proc
umount $target/dev/pts
umount $target/dev
EOT

chmod a+x $target/enter

exit 0

