#!/bin/bash

# Requires "usta" to be configured in .ssh/config.
# Something like:
# Host  usta
# HostName login.usta.de
# User XXX
# IdentityFile ~/.ssh/id_rsa


ssh -i ~/.ssh/wahlbet_key wahlprognose@asta-wahl.asta.uni-karlsruhe.de wahl/Client/wahlbet/wahlbet.py wahl/Client/wahlbet/templates/wahlbet.html > /tmp/wahlbet.html

#TODO
#scp /tmp/wahlbet.html usta:/www/UStA/Wahl/wahlbet_2011.html
#ssh usta chgrp wahl /www/UStA/Wahl/wahlbet_2011.html
#ssh usta /usr/usta/OpenBSD/bin/publish wahl

exit 0

